from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('home/', views.indexLater, name = 'index-later'),
    #path('', views.salepage, name = 'for-sale-homes'),
    path('salepagedetails/<int:id>/', views.salepagedetails, name = 'salepagedetails'),
    path('rentpagedetails/<int:id>/', views.rentpagedetails, name = 'rentpagedetails'),
    path('salesearch/', views.salesearch, name = "sale-search-results"),
    path('rentsearch/', views.rentsearch, name = "rent-search-results"),
    path('search/', views.SalesDocumentView.as_view({'get': 'list'}), name = 'elastic-search'),
    path('salesearchblock/', views.salesearchblock, name = 'sale-search-block'),
    path('login/', views.loginview, name = 'login'),
    path('signup/', views.signupview, name = 'signup'),
    path('logoutpage/', views.logoutpage, name = 'logoutpage'),
    path('sales-documents/', views.SalesDocumentView.as_view({'get': 'list'}), name = 'elastic-view-results'),
    path('elastic-result/', views.elasticview, name = 'sales-document-lists'),
    path('blogs/', views.blogs, name = 'blogs'),
    path('blogpost/', views.blogpost, name = 'blog-detail'),
    path('soldsearch/', views.soldsearch, name = 'sold-search-results'),
    path('soldpagedetails/<int:id>/', views.soldpagedetails, name = 'soldpagedetails'),
    path('agents/', views.agents, name = 'agent-results'),
    path('agentdetails/<str:agent_name>/', views.agentdetails, name = 'agent-details'),
    path('sales-filter', views.salesfilter, name = 'sales-filter'),
    path('account/', views.account_view, name = 'account-view'),
    path('save_sale/', views.save_sale, name='save_sale'),
    path('my_saves/', views.my_saves, name='my_saves'),
    path('get_saved_sales/', views.get_saved_sales, name='get_saved_sales'),
    path('agentsignup/', views.agentsignupview, name = 'agent-signup'),
    path('agent-login/', views.agentloginview, name = 'agent-login'),
    path('rent-filter', views.rentfilter, name = 'rent-filter'),
    path('sold-filter', views.soldfilter, name = 'sold-filter'),
    path('account/<int:id>/', views.agentFormView, name = 'agent-form'),
    path('editsales/<int:id>/', views.agentEdit, name = 'edit-sales'),
    path('aboutus/', views.aboutus, name = 'about-us'),
    path('addListing/', views.add_new_listing, name = 'add-new-listing'),
    path('delete/<int:id>/', views.delete_listing, name='delete-listing'),
    path('sendanemail/', views.sendanemail, name = 'email'),
    path('inquiry/', views.inquiryView, name = 'inquiry'),
    path('inquiryReal/', views.inquiryViewReal, name = 'inquiry-real'),
    path('inquirySales/<int:id>/', views.inquiryViewSale, name = 'inquiry-sale'),
    path('inquiryRentals/<int:id>/', views.inquiryViewRent, name = 'inquiry-rent'),
    path('inquirySold/<int:id>/', views.inquiryViewSold, name = 'inquiry-sold')
]