# Generated by Django 5.0.3 on 2024-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='special_values',
            fields=[
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('special1', models.TextField(blank=True, db_column='special1', null=True)),
                ('special2', models.TextField(blank=True, db_column='special2', null=True)),
                ('special3', models.TextField(blank=True, db_column='special3', null=True)),
                ('special4', models.TextField(blank=True, db_column='special4', null=True)),
                ('special5', models.TextField(blank=True, db_column='special5', null=True)),
                ('special6', models.TextField(blank=True, db_column='special6', null=True)),
                ('special7', models.TextField(blank=True, db_column='special7', null=True)),
                ('special8', models.TextField(blank=True, db_column='special8', null=True)),
                ('special9', models.TextField(blank=True, db_column='special9', null=True)),
                ('special10', models.TextField(blank=True, db_column='special10', null=True)),
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False)),
            ],
        ),
    ]
