# Generated by Django 5.0.3 on 2024-04-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateApp', '0002_special_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special_values',
            options={'managed': False},
        ),
    ]
