# Generated by Django 5.0.3 on 2024-04-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateApp', '0003_alter_special_values_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='special_values',
            table='special_values',
        ),
    ]
