# Generated by Django 5.0.3 on 2024-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateApp', '0005_specialvalues_delete_special_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True, db_column='state', null=True)),
                ('city', models.TextField(blank=True, db_column='city', null=True)),
                ('agent_name', models.TextField(blank=True, db_column='agentName', null=True)),
                ('agency', models.TextField(blank=True, db_column='agency', null=True)),
                ('specialities', models.TextField(blank=True, db_column='specialities', null=True)),
                ('about_me', models.TextField(blank=True, db_column='aboutMe', null=True)),
                ('broker_address', models.TextField(blank=True, db_column='brokerAddress', null=True)),
                ('cellphone', models.TextField(blank=True, db_column='cellphone', null=True)),
                ('brokerphone', models.TextField(blank=True, db_column='brokerphone', null=True)),
                ('screenname', models.TextField(blank=True, db_column='screenname', null=True)),
                ('member_since', models.TextField(blank=True, db_column='memberSince', null=True)),
                ('licenses', models.TextField(blank=True, db_column='Licenses', null=True)),
                ('other_licenses', models.TextField(blank=True, db_column='otherLicenses', null=True)),
                ('language1', models.TextField(blank=True, db_column='Language1', null=True)),
                ('language2', models.TextField(blank=True, db_column='Language2', null=True)),
                ('image_url', models.TextField(blank=True, db_column='ImageURL', null=True)),
            ],
            options={
                'db_table': 'agentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('body', models.TextField(blank=True, db_column='body', null=True)),
                ('date_added', models.DateTimeField(blank=True, db_column='dateAdded', null=True)),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='title', null=True)),
                ('slug', models.TextField(blank=True, db_column='slug', null=True)),
                ('intro', models.TextField(blank=True, db_column='intro', null=True)),
                ('body', models.TextField(blank=True, db_column='body', null=True)),
                ('image', models.TextField(blank=True, db_column='image', null=True)),
                ('date_added', models.DateTimeField(blank=True, db_column='dateAdded', null=True)),
            ],
            options={
                'db_table': 'blogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.IntegerField()),
            ],
            options={
                'db_table': 'saved_sale',
                'managed': False,
            },
        ),
    ]
